---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lg
  template:
    metadata:
      labels:
        app: lg
      annotations:
        linkerd.io/inject: disabled
    spec:
      containers:
      - image: grafana/k6:0.47.0
        name: k6
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 125m
            memory: 64Mi
        env:
          - name: TOTAL_ARRIVAL_RATE
            value: "10"
          - name: DURATION
            value: "1h"
          - name: K6_PROMETHEUS_RW_SERVER_URL 
            value: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
          - name: K6_PROMETHEUS_RW_TREND_STATS
            value: p(95),p(99),avg
        command:
          - "k6"
          - "run"
          - "-o"
          - "experimental-prometheus-rw"
          - "/scripts/script.js"
        volumeMounts:
        - mountPath: /scripts/
          name: script
      volumes:
      - configMap:
          items:
          - key: script.js
            path: script.js
          name: lg-script
        name: script
